project:
  type: website
  render:
    - /chapters/*.qmd
    - index.qmd
    - "/cards/**/*.qmd"
  post-render:
    - "cp -rnv static/. _site/"

website:
  title: "Mise en production de projets data science"
  navbar:
    background: "#4758AB"
    align: center
    collapse-below: lg
    left:
      - href: index.qmd
        text: Home
      - href: chapters/introduction.qmd
        text: Introduction
      - href: chapters/linux-101.qmd
        text: Linux 101
      - href: chapters/git.qmd
        text: Git
      - href: chapters/code-quality.qmd
        text: Qualité du code
      - href: chapters/projects-architecture.qmd
        text: Architecture des projets
      - href: chapters/portability.qmd
        text: Portabilité
      - href: chapters/deployment.qmd
        text: Mise en production
      - href: chapters/application.qmd
        text: Application
      - href: chapters/evaluation.qmd
        text: Evaluation

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

eval: false
author: "Romain Avouac et Lino Galiana"
