project:
  type: website
  render:
    - /chapters/*.qmd
    - /additional/*.qmd
    - index.qmd
  post-render:
    - "cp -rnv static/. _site/"

website:
  title: "Mise en production des projets de data science"
  sidebar:
    - id: rappels
      title: "Les bases"
      style: 'docked'
      collapse-level: 2
      contents: 
        - chapters/introduction.qmd
        - chapters/linux-101.qmd
        - chapters/git.qmd
    - id: quality
      title: "Qualité du code"
      collapse-level: 0
      contents: 
        - chapters/code-quality.qmd
    - href: chapters/portability.qmd
      text: Portabilité

  navbar:
    background: "#c95a26"
    search: true
    align: center
    collapse-below: lg
    left:
      - sidebar:rappels
      - href: chapters/code-quality.qmd
        text: Qualité du code
      - href: chapters/projects-architecture.qmd
        text: Architecture des projets
      - href: chapters/portability.qmd
        text: Portabilité
      - href: chapters/deployment.qmd
        text: Mise en production
      - href: chapters/application.qmd
        text: Application
      - href: chapters/evaluation.qmd
        text: Evaluation
      - icon: github
        menu:
          - text: Site web
            url:  https://github.com/ensae-reproductibilite/website
          - text: Slides
            url:  https://github.com/ensae-reproductibilite/slides
          - text: Application fil rouge
            url:  https://github.com/ensae-reproductibilite/application-correction


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

eval: false
author: "Romain Avouac et Lino Galiana"
sidebar: false
