name: Publish slides

on: 
  push:
    branches:
      - main
      - master
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          version: 1.4.515
      - name: Install Python and Dependencies
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
      - run: pip install jupyter
      - name: Publish to GitHub Pages (and render)
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        #env:
        #  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
